from Bio.Seq import Seq

s = Seq("AAGCGGGGCGCGGGGCCGCGGGGCGCGGGGCTCTTCCGCGGGGCTGTGCGGGGCCCCCGGCGGGGCCGCGGGGCCGCGGGGCCCAAGAATGAATGCGGGGCTTAACGCGGCGGGGCGCGGGGCAGGCGGGGCGCGGGGCGCGGGGCGCGGGGCCGCGGGGCAGCGGGGCTAACCGAGCGGGGCGGGGAGCGGGGCCTCACGGTAGCGGGGCCATGGCGGGGCAAGCGGGGCGCGGGGCTGCGGGGCCAAAACTAGACTGCGGGGCTCGCGGGGCACAGCGGGGCGCGGGGCGGCCGATGGCGGGGCGAGCGGGGCAACTTCGCGGGGCGCGGGGCATGAACTAATGACAGCGGGGCTGGCGGGGCGGGCAAGCGGGGCGCGGGGCCGAGTTGCGGGGCGCGGGGCGGCGGGGCCGGCGGGGCGCGGGGCTTCAGCGGGGCGCGGGGCGCGGGGCCCGCGGGGCGGACGCGGGGCACAGCGGGGCGCGCGGGGCGCGGGGCGCGGGGCGGCGGGGCGCGGGGCGCGGGGCCCGGCGGGGCCGGGCGGGGCGGCGCGGGGCAAGCGGGGCTTGCGGGGCTTGCGGGGCGCGGGGCGCGGGGCACGCGGGGCGTTCAGATACTGCGGGGCGGTGAGACGGCGGGGCAGCGGGGCGGCGGGGCAATTTAGCTGCGGGGCGCGGGGCGCGGGGCGCGGGGCGGCGGGGCCGCGGGGCGGCGGGGCGCGGGGCTTGCGGGGCAGCAGCCCCGCGGGGCTCGTGTTTCCGCGGGGCAGTCGGCGGGGCGTGCGGGGCCACAGGCGGGGCGAGCGGGGCTCGCGGGGCAGTAGCGGGGCGCGGGGCAGGTTCTGCGGGGCGCGGGGCGCGGGGCTGCGGGGCAGCGGGGCAGCGGGGCTGTATATTATGAGGACTTATCGCGGGGC".replace("\n", "").strip())
t = Seq("GCGGGGCGC".replace("\n", "").strip())#motifs

#empty list
positions = []

#len of s  is largers
#len of t is smaller
#why we subtract ,i dont want the loop to go inside s till last character , becuase the len of t is smaller
for i in range(len(s) - len(t) + 1):
    if s[i:i+len(t)] == t: #indexing we used
        positions.append(i + 1)  # 1-based indexing

print(*positions)